/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cad4efbd255ff2d7515f5aa490245fbe)
interface __BaseEnv_Env {
	LANGSMITH_PROJECT: "context-plane-mcp";
	LANGSMITH_TRACING: "true";
	MONGODB_DATABASE: "context_plane";
	CONTEXT_PLANE_ORG_ID: "org_synthetic_demo";
	CONTEXT_PLANE_PROJECT_ID: "project_mvp_02";
	CONTEXT_PLANE_COORDINATION_SCOPE: "project:context-plane";
	MONGODB_URI: string;
	CONTEXT_PLANE_API_TOKEN: string;
	LANGSMITH_API_KEY: string;
	BRAIN: DurableObjectNamespace<import("./src/index").BrainContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BrainContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LANGSMITH_PROJECT" | "LANGSMITH_TRACING" | "MONGODB_DATABASE" | "CONTEXT_PLANE_ORG_ID" | "CONTEXT_PLANE_PROJECT_ID" | "CONTEXT_PLANE_COORDINATION_SCOPE" | "MONGODB_URI" | "CONTEXT_PLANE_API_TOKEN" | "LANGSMITH_API_KEY">> {}
}
