/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 94659b0194b1d13ededb29edbea27ebf)
interface __BaseEnv_Env {
	MONGODB_DATABASE: "context_plane_poc";
	CONTEXT_PLANE_ORG_ID: "org_demo";
	CONTEXT_PLANE_PROJECT_ID: "project_context_plane";
	MONGODB_URI: string;
	CONTEXT_PLANE_API_TOKEN: string;
	BRAIN: DurableObjectNamespace<import("./src/index").BrainContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BrainContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MONGODB_DATABASE" | "CONTEXT_PLANE_ORG_ID" | "CONTEXT_PLANE_PROJECT_ID" | "MONGODB_URI" | "CONTEXT_PLANE_API_TOKEN">> {}
}
